### ISSUE TITLE
FEATURE: DigitalOcean marketplace droplets should be based on Ubuntu 20.04LTS

### ISSUE THREAD

**Issue by sunny75016** [ultrahorizon/UH-VPN-Docs#14]
As a corporate user, we try to use the latest LTS of operating systems whenever feasible. Currently the DO marketplace droplet is based on Ubuntu 18.04 whereas Ubuntu 20.04 is already doing well with long term support expected to last much longer.

Grateful if you could consider repackaging future droplets with Ubuntu Focal Fossa 20.04.

**Comment by jwsi** [comment]
So as you can see from our [PPA Package Archive](https://launchpad.net/~ultrahorizon/+archive/ubuntu/ppa/+packages), `uh-vpn-server` v1.0.1 is actually only published on bionic and this is why at present the DO droplet is based on 18.04.

We're currently transitioning to uh-vpn-server 1.1.0 which will introduce dynamic config updates (vs polling in v1.0.1) and this will be available on Ubuntu bionic through to groovy. Reason for delay in release was due to a couple of hitches with the python3-waitress package (dependency for uh-vpn-server 1.1.0) whereby it had some Linux bugs, and Ubuntu don't sync their python3 packages with PyPi beyond initial release, so we had to compile our own version of python3-waitress and host it on the PPA to avoid issues (this is now done).

**In any case, once v1.1.0 is released on our PPA, we will merge the downstream digital ocean builds to use focal (20.04). This should be done within a week or so, then it'll be up to Digital Ocean to review the new image (add another week).**

**Comment by jwsi** [comment]
Our upstream [PPA](https://launchpad.net/~ultrahorizon/+archive/ubuntu/ppa/+packages) on launchpad now has builds for `uh-vpn-server` on bionic through to groovy. The new Digital Ocean image running on `focal` is now pending review.

**Comment by jwsi** [comment]
The new image running `uh-vpn-server` v1.1.0 on Ubuntu 20.04 (focal) has now been approved by Digital Ocean and is available here:

https://marketplace.digitalocean.com/apps/uh-vpn

Closing this issue now.
