### ISSUE TITLE
FEATURE: More security control by over-riding the vpn.conf default settings.

### ISSUE THREAD

**Issue by sunny75016** [ultrahorizon/UH-VPN-Docs#16]
All changes made by customers to the local file vpn.conf get erased with every reboot (it seems). For example, we made the following changes (being our security preferences):

compress 
#removing lz4-v2 - so there is no compressions (yes, I know openvpn limitations)

tls-version-min 1.3
#instead of default 1.2

It will be great if either an ".local" file override (much easier to implement via bash or sed) or a server side options (more painful to implement due to UI) could be considered. Thanks.

**Comment by jwsi** [comment]
@sunny75016 the vpn.conf file is generated dynamically by the uh vpn server software. Any custom directives inserted there will be erased whenever the service restarts or a config update is pushed to the server by the UH VPN API. **It should not be changed manually**.

We are actively looking to expand the feature set for premium customers. However, this requires client side support (UH VPN Apps). Furthermore, a custom local override file would also produce differing configurations for clients and servers as your local changes would not be visible to the UH VPN API which pushes configs to clients. Therefore any changes **must** be done through the web interface.

We will look at introducing the possibility of altering compression settings and updating TLS to version 1.3 and you will see options for this in the web interface if and when they become available. A reduced set of compression options should definitely be possible; for example, compression enabled = lz4v2, compression disabled = none.

A note on TLS, it's currently at version 1.2 because all of our client applications support version 1.2 and version 1.3 has not been tested. The majority of TLS 1.3 improvements would only improve the initial handshake speed and so there aren't an awful lot of security or performance improvements to be made here, so this is a low priority improvement for our dev team.

**Comment by jwsi** [comment]
I'll implement the ability to enable/disable compression in `uh-vpn-server` 1.1.0, then once our internal team has tested that the clients can handle this, we'll provide the option in the web interface. Expect around 2 weeks for this to appear.

**Comment by sunny75016** [comment]
Absolutely fine. You and the UH team are doing an excellent professional job. Kudos!  (Also for your information - in my experimental lab - I replaced the default kernel of the droplet with the latest 5.6.15, manually upgraded openssl to 1.1.1g and openssh to 8.2p1......and guess what, UH-VPN works absolutely fine. All my end points are iphones and ipads.)

**Comment by jwsi** [comment]
Thanks for the positive feedback @sunny75016. People like you really do help as it gives our development team fresh ideas and allows us to identify issues that we haven't picked up.

Great to hear that the kernel upgrade worked!

**Comment by jwsi** [comment]
This has now been implemented and requires `uh-vpn-server` v1.1.0. If compression is enabled on the web interface, the VPN tunnel will use LZ4v2. If disabled, no compression will occur at all.

To upgrade to the latest server software execute the following:

`sudo apt-get update`
`sudo apt-get install uh-vpn-server`

One **must ensure** that the port `TCP 2802` is open by any firewall you are using on the server (e.g. Digital Ocean Firewall) as the new server software uses dynamic config notifications instead of minute by minute polling in order to ensure faster config updates for servers.
