### ISSUE TITLE
FEATURE: Spanish Translation

### ISSUE THREAD

**Issue by Takumi86ES** [ultrahorizon/UH-VPN-Docs#20]
Very good work to the ultra horizon team.

I volunteer to help translate the website, applications and help documents into Spanish.

**Comment by AnthonyWharton** [comment]
Thanks for the offer! Translating UH VPN helps make it available to more users which is great!

Currently the Apps are *almost* ready to have translations dropped in place, so I can make the English “strings files” available for translation and we can then create a Spanish equivalent. I’m currently finishing the Windows deployment and will add this to my todo list afterwards.

I know our documentation service, Read the Docs, certainly [supports translation](https://docs.readthedocs.io/en/stable/localization.html) however I’m not familiar with the process yet. It looks like we may need to create a new documentation project. We can look into this and continue here when we know the next steps. One thing to note is the documentation is evolving fairly rapidly as UH VPN is early in development, so translations may require updating frequently. If this is too much work then we can aim to translate this once pages are finalised.

Finally, the website may require a little bit more work although I’m not too sure, I’ll leave that to @jwsi to answer as I’m less familiar with then localisation pipeline there.

**Comment by jwsi** [comment]
@Takumi86ES thank you very much for offering to translate our platform into Spanish, this will be a great help moving forward. 👍

@AnthonyWharton is right, the first step will be translating the applications which involves localising strings such as "Manage Profiles", "Connecting to UH VPN" and so on which should be very simple. This would be a great start as we have built in support for this. Then we can release updates to the applications such that the default language is Spanish for relevant App Store/Play Store regions. If you email [engineering@ultra-horizon.com](mailto:engineering@ultra-horizon.com), Anthony will be able to provide you with a list of phrases to translate into Spanish.

With regards to the docs, this should be simple too. We can add subdirectories for each language within this repository and then the Spanish documentation would be served under https://docs.uh-vpn.com/es/latest. However, we'd like to hold off translations for this until we have fully refined the English version as things are still subject to change.

On the website front, this is perhaps the most complex as we'd have to detect the region of the user based on their IP address which is always a bit hit and miss. Therefore a good first step would be to include a lanugage dropdown to allow users to select languages. Once I've built the framework in order to do this, translations for the website will be possible.

But in any case, the application translations would be a great place to start 👍

**Comment by marina8888** [comment]
Once you are ready, feel free to add a column on that spreadsheet for Russian and loop me in. Might be able to do Japanese for basic phrases (website front page, management page) etc. if u need, but not for the full documentation. I'll leave it up to you to decide.

**Comment by AnthonyWharton** [comment]
Thanks @marina8888. I will be working on this in the coming weeks.
