### ISSUE TITLE
BUG: Tray icon disappeared in Windows10. Not reappearing even after the registry patch merge. Needs a kill switch.

### ISSUE THREAD

**Issue by sunny75016** [ultrahorizon/UH-VPN-Docs#34]
Using Windows10 Pro 1909 fully uptodate. The UH-VPN icon does not appear after reboot. I have to manually run the Start / Programs route. I have tried the automatic .reg patch in the previous bug report, but that does not work.

I checked that the Windows Service (UH daemon) is enabled. I also checked in the Task Manager that the daemon is working. Until the icon reappears the VPN does not work.

I would like UH VPN to act as the "kill switch" so that we do not have to remember to start the VPN after every boot. It should work automatically. My UH version is 1.0.1

**Comment by AnthonyWharton** [comment]
Hi Sunny,

To run UH VPN you need to have both the daemon and client open (in the Details tab in Task Manager you should see `uh-vpn.exe` and `uh-vpn-daemon.exe`). The daemon simply runs the VPN core and is a system service to allow for persistent elevated privileges, otherwise the client would have to ask for Admin rights upon every launch/connection which makes for a bad UX.

If you launch UH VPN does can you restore VPN connectivity?

I’m about to release 1.0.2 (in the next few hours) which should increase stability between the daemon and client, so if you cannot launch UH VPN please standby for that.

Finally, launch on boot is another feature request (#9) which I am planning to tackle on all platforms next. We’ve had a few teething issues with the release of UH VPN Windows on certain machines, so I hope you can understand those have been the top priority.

Thanks,
Anthony

**Comment by AnthonyWharton** [comment]
As an aside, “kill switch”s are slightly buzz wordy and used with slightly different meanings across different VPN providers so could you clarify (explain like I’m 5!) what exactly you mean/would like?

**Comment by sunny75016** [comment]
1) My expectation from a "kill switch" is that the smartphone, tablet or laptop should block all data transfer outside the VPN connection. The objective is to avoid data being leaked outside the approved VPN traffic.
2) No problems. I will wait for the new version. In the meanwhile, the manual start allows proper VPN operation.

**Comment by AnthonyWharton** [comment]
Great, glad it’s working. Start in boot won’t be in the new update, but will be coming soon! Keep an eye out!

**Comment by AnthonyWharton** [comment]
Update: UH VPN Windows 1.0.2 is out, please find the download link on the uh-vpn.com homepage! :)
