### ISSUE TITLE
FEATURE: Require pincode to disable vpn on smartphone app

### ISSUE THREAD

**Issue by sunny75016** [ultrahorizon/UH-VPN-Docs#35]
At the back-end of UH VPN, I have included family friendly filters by channeling the DNS lookups. However, if my children can easily disable the VPN, that protection is no longer effective.

It would be great to set a pin code (or Face ID) for the "disconnect" button.

Thanks for considering.

**Comment by AnthonyWharton** [comment]
I like this idea in theory, we could offer a pin/biometric locks to our apps, however there are a few problems with this.

On iOS/macOS, we make use of the `NetworkExtension` framework in order to comply with App Store rules, this is why you can see the VPN in the system settings.  Apple likes to take a pro-user stance with privacy, and thus VPN's can always be enabled/disabled from the settings of the device, so a pin code would not lock the VPN on I am afraid.  All it would offer is protection on profile management, which is only accessible from within the app.

I'll add it to the backlog and leave this issue open for discussion, but this is definitely a lower priority item for now.

Thanks for your understanding,
Anthony

**Comment by jwsi** [comment]
Hi @sunny75016,

Unfortunately, this feature isn't possible due to OS workarounds making a pin/biometric option pretty pointless. If operating systems like iOS or Android provide some sort of API in the future which allows UH VPN to request user authentication when users alter the VPN state in the standard settings menu, then we'll re-open this issue and discuss a potential implementation path.

James.
