### ISSUE TITLE
QUESTION: Run Pi-Hole on Ubuntu VM?

### ISSUE THREAD

**Issue by CobraThief** [ultrahorizon/UH-VPN-Docs#36]
Hello,

Would it be possible to run pi-hole on the Ubuntu appliance provided by UH? When I attempted to install it, nothing would resolve. DNS resolution is required to install and run pi-hole. I'm running the AWS Marketplace AMI.

After making some changes to the netplan config file to put a DNS server in it, the desktop app would no longer connect. Wonder what I broke by adding DNS resolution to it...

Would it be possible to do this? If there is a better approach (i.e. create a completely separate server running pi-hole within the same LAN space), please let me know. If there's any other info needed from me, I'll provide that appropriately.

Thanks!

P.S. I did increase the disk size when creating the instance, just FYI.

**Comment by AnthonyWharton** [comment]
I should have thought it would be ok to run Pi-hole on the same instance as UH VPN, bearing in mind if you want more clients/traffic going through the machine you may require an instance with a higher specification.  With that said I haven't looked at the Pi-hole stack in a little while so I will need to have a look to see if anything conflicts.

From just your question it's hard to know what exactly is going wrong, and I won't claim to be a Pi-hole expert, but here's a few fairly general bits of troubleshooting advice:

1. Basics first, if Pi-hole doesn't even work on your AWS instance, check your instance security group is allowing traffic that Pi-hole requires - it looks like they have those documented here: https://docs.pi-hole.net/main/prerequisites/#ports.
2. If UH VPN clients are failing to connect to the server, it will likely mean that either your UH VPN server is misconfigured and that the server it failing to start, or that something in your Pi-hole setup is blocking it.
3. If UH VPN clients are connecting to the server but then have no connectivity, it will likely mean that you need to ensure your UH VPN server's DNS serttings are set to point to the DNS server that Pi-hole has set up on your instance.

Other thing to note:

 - After editing a server, allow a short amount of time for the UH VPN server to get pushed the changes and restart the VPN server with your changes.
 - You may have some hints as to what is failing with the UH VPN server in the [on-system logs.](https://docs.uh-vpn.com/en/latest/servers/logging.html)

If I get some time, I'll see if I can have a go at setting this up myself later and see if I run into the same issues as you, as I haven't used Pi-hole for some time! In the mean-time @jwsi may have more experience with this than I do!

**Comment by jwsi** [comment]
So there are two options here:

1) Create two separate instances. One for PiHole and another for UH VPN and set up UH VPN Servers to point to the PiHole instance for DNS resolution.
2) Run them concurrently on the same instance. If doing this I think it would make sense to install PiHole first and check resolution works to localhost. I.e. `dig test.com @127.0.0.1` etc... Once that works, install UH VPN and see if you experience issues once they're running together. I think from our point of view it would be easier to debug if you had a proven working PiHole installation first, then we can ascertain why UH VPN is causing issues 👍

**Comment by CobraThief** [comment]
Thanks jwsi & AnthonyWharton for responding.

When attempting to install, I first spun-up the UH VPN AMI and made sure it worked. After having my endpoint connected to UH VPN, I then attempted the pi-hole install.

I could not get pi-hole to install, because it seems like there is no DNS configured on the UH VPN. When attempting to run the 'curl' command to install it, it is failing because it cannot resolve names to pull down the various bits it needs to run. After making a change to netplan, and then rebooting the instance I consoled back into the instance (while not on UH VPN). I could see that names would then resolve. However, when trying to connect with my laptop endpoint, the status would hang on 'connecting'.

I'll give jwsi's #2 a go, and see if that does the trick!

**Comment by AnthonyWharton** [comment]
I'm currently having a play about with this now, I managed to get Pi-hole installed and as far as I can tell it seems to work... When the DNS settings are set correctly.

The issue I am currently diagnosing is that `/etc/resolv.conf` is currently set by `systemd-resolved`. Manually adding `nameserver 127.0.0.1` to `/etc/resolv.conf` will fix DNS resolution temporarily, and this is what has allowed me to check Pi-hole is indeed working. However as this file is generated this gets overwritten on a fairly regular basis.

Infuriatingly, the [`netplan` settings as recommended by AWS](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-static-dns-ubuntu-debian/) do not seem to stick, so I'm currently looking into why this is - I believe that perhaps systemd's DNS resolution is conflicting with `dhcpd5` [as installed by Pi-hole](https://docs.pi-hole.net/main/prerequisites/#ip-addressing), but this is just a working theory at the moment and I will keep you posted :)

**Comment by AnthonyWharton** [comment]
Ok, sorry it's been a little while.  I've had some success with this. Before the following, I created a UH VPN server [according to the UH VPN AWS setup docs](https://docs.uh-vpn.com/en/latest/setup-guides/aws.html), and then installed Pi-hole [as per their steps](https://docs.pi-hole.net/main/basic-install/) - cloning their repository (Alternative 1).  Note that you will need to allow inbound port 53 (UDP/TCP) and port 80 (TCP) in your AWS instance security group.

**Like you, I got a nameserver issue during installation** due to `systemd-resolved` not playing nice. The installer will keep retrying for 120 seconds, so whilst the installer is retrying open another SSH session and temporarily add another DNS server to your `/etc/resolv.conf`, e.g. adding the line `nameserver 1.1.1.1` (Cloudflares DNS service). This should allow the installer to finish, however that was only a **temporary** fix.

In short, to get things working a bit more robustly with Pi-hole, I then disabled `systemd-resolved` allowing `dhcpcd` to act unrestricted, and then set up my UH VPN server to have the private IP address of the AWS instance as the DNS server.

If you want the full steps of what I did then carry on reading and if you run into any issues feel free to get in touch:

### Full Steps: 

 1) I disabled `systemd-resolved` as the netplan rules did not seem to apply properly.
    ```
    sudo systemctl stop systemd-resolved
    sudo systemctl disable systemd-resolved
    ```

 2) Once disabled I removed the symlink `sudo rm /etc/resolv.conf` that was pointing to `/run/systemd/resolve/stub-resolve.conf`.

 3) Next I ensured that `dhcpcd` was running (`sudo systemctl status dhcpcd`), and that the config that Pi-hole had put in `/etc/dhcpcd.conf` looked correct according to my AWS VPC settings. 

    This might vary a little bit for you, but in my case my AWS instance had the following:
    ![2020-07-09 12 10 08](https://user-images.githubusercontent.com/7091722/87032861-26bbda80-c1dd-11ea-8cb5-2dab3a32be56.jpg)
    And my `dhcpcd.conf` had the same details (you can see more details in AWS by clicking on the VPC/Subnet that is attached to your instance), as well as my selected DNS provider (Cloudflare):
    ```
    ubuntu@UH-VPN:~$ tail /etc/dhcpcd.conf
    
    # Generate Stable Private IPv6 Addresses instead of hardware based ones
    slaac private
    interface ens5
            static ip_address=172.16.0.4/24
            static routers=172.16.0.1
            static domain_name_servers=1.1.1.1 1.0.0.1
    ```

 4) I then rebooted my machine and noted that `dhcpcd` had repopulated `/etc/resolv.conf` with the Cloudflare DNS servers:
    ```
    ubuntu@UH-VPN:~$ tail /etc/resolv.conf

    # Generated by dhcpcd from ens5.dhcp
    # /etc/resolv.conf.head can replace this line
    nameserver 1.1.1.1
    nameserver 1.0.0.1
    # /etc/resolv.conf.tail can replace this line
    ```
    You can verify that DNS is working with some dig commands.  Note that from the command line, pi-hole will not work, so you will need to manually specify `@127.0.0.1` in your dig command. For testing, I found a domain that was in one of the default block lists in Pi-hole (fgoogle.com) and tested everything was working locally as expected:
    ![Screenshot 2020-07-09 at 12 41 56](https://user-images.githubusercontent.com/7091722/87035907-eca10780-c1e1-11ea-9a74-c05e77c9912a.png)

 5) Now that everythign was working, I disabled port 80 access in my security group to restrict access to the Pi-hole web interface, and modified the UH VPN server to set the DNS server as the private IP address of the instance, you will have seen this in step 3 - in this example case mine was `172.16.0.4`.  I hit save and then made sure the settings applied properly:

    ```
    ubuntu@UH-VPN:~$ tail /var/log/uh-vpn-server/daemon.log

    2020-07-09 11:32:01,410 - uh-vpn-server - INFO - Processing update request for server: UDP - Filtered
    2020-07-09 11:32:01,485 - uh-vpn-server - INFO - Successful update request for server: UDP - Filtered

    ubuntu@UH-VPN:~$ tail /var/log/uh-vpn-server/<server_id>.log

    ...
    Thu Jul  9 11:32:06 2020 Initialization Sequence Completed
    ```

Now I can connect to my UH VPN server and Pi-hole works as expected (I can access the web interface through the VPN on the instance's private IP address).

**Comment by CobraThief** [comment]
Awesome response and write-up Anthony! Thanks for taking the time to do this.

I was putzing around and wimped-out spinning up another instance to run pi-hole. I got that all working except the web interface, which I cannot figure out since I can ping it ok and DNS resolution is working. But... your solution consolidates to 1 instance, so that's that!

Thanks again!

**Comment by AnthonyWharton** [comment]
No worries, looking into turning it into a guide as there's definitely been some interest in this, so decided to take a little extra time :)

Spawning another instance would certainly be easier, you'll want to make sure they're on the same VPC/subnet and then you should be able to specify the VPC private subnet addresses to set the DNS server on your UH VPN server, as well as to connect to the web interface - when on the VPN of course!

If you're still having issues double check that ports are open in your security group and that you are using the correct IP's!

Thanks for using and enjoying UH VPN 🎉

**Comment by CobraThief** [comment]
Thanks again, Anthony! I finally got around to doing this tonight, and your instructions worked perfectly. I added multiple devices and went premium also, happy to do it for a fine product with responsive dev's.

**Comment by AnthonyWharton** [comment]
Fantastic, glad to hear it worked well for you and thanks for subscribing! 💪 If you have any other issues or feature requests then you know where to find us!

Anthony
