### ISSUE TITLE
QUESTION: How to disable ipv6?

### ISSUE THREAD

**Issue by hybtoy** [ultrahorizon/UH-VPN-Docs#50]
Hello, 

How to correctly disable ipv6 on uh-vpn? 

When I am turning off "redirect ipv6 traffic" and remove ipv6 subnet, control panel tells me that 

`Server modification failed! Server reported status code: 1300 Code Information`

I am turning off ipv6 on my VPS via sysctl, restart the uh-vpn-server and I receive fatal error:

`Sat Oct 10 17:48:53 2020 /sbin/ip -6 addr add fe80::1/64 dev tun0
RTNETLINK answers: Permission denied
Sat Oct 10 17:48:53 2020 Linux ip -6 addr add failed: external program exited with error status: 2
Sat Oct 10 17:48:53 2020 Exiting due to fatal error`

**Comment by jwsi** [comment]
Hi @hybtoy ,

If you don't have an allocated IPv6 subnet from a Internet authority (e.g. RIPE) then you should leave the IPv6 tunnel network set at: `fe80::/64` and the "Redirect all IPv6 traffic" to on. This will block all IPv6 traffic from egressing.

Without these parameters set your clients with IPv6 connectivity will leak IPv6 connections over a regular Internet connection and they will not be routed through the VPN. With these options set all IPv6 traffic will never get forwarded upstream and IPv6 routing will be disabled and stopped at the VPN server.

You encounter that code because the server software will not let you remove the IPv6 subnet in an effort to prevent IPv6 leakage.

**Comment by hybtoy** [comment]
> Hi @hybtoy ,
> 
> If you don't have an allocated IPv6 subnet from a Internet authority (e.g. RIPE) then you should leave the IPv6 tunnel network set at: `fe80::/64` and the "Redirect all IPv6 traffic" to on. This will block all IPv6 traffic from egressing.
> 
> Without these parameters set your clients with IPv6 connectivity will leak IPv6 connections over a regular Internet connection and they will not be routed through the VPN. With these options set all IPv6 traffic will never get forwarded upstream and IPv6 routing will be disabled and stopped at the VPN server.
> 
> You encounter that code because the server software will not let you remove the IPv6 subnet in an effort to prevent IPv6 leakage.

Hey James,

Thanks for the reply. I understand now.

What about fatal error when I am turning off ipv6 on the server?

Thanks.

**Comment by jwsi** [comment]
Hey @hybtoy,

You'll need to leave IPv6 enabled on the server in order to prevent IPv6 leaks. The error you're seeing on the server software is because you've disabled IPv6 and therefore, cannot add an IPv6 route into the routing table.

James.
