### ISSUE TITLE
QUESTION: About security

### ISSUE THREAD

**Issue by sunny75016** [ultrahorizon/UH-VPN-Docs#53]
Hi Alex, Hi James, Thanks for the great work. I have a question simply out of well-published reports of attacks on certain VPNs (article here - https://threatpost.com/apt-groups-exploiting-flaws-in-unpatched-vpns-officials-warn/148956/). That article also mentioned - 

> A more comprehensive list of mitigation techniques recommended by the NSA also includes discouraging the use of proprietary SSLVPN/TLSVPN protocols and self-signed and wild card certificates for public-facing VPN web applications; requiring mutual certificate-based authentication so remote clients attempting to access the public-facing VPN web application must present valid client certificates to maintain a connection; and using multi-factor authentication to prevent attackers from authenticating with compromised passwords by requiring a second authentication factor.

I am not so worried about the first part - as UH is using OpenVPN and not proprietary protocols.
However, it seems there is self-signed certificate usage and there is no multi-factor authentication. 

Your views on whether the above is relevant to UH from a security perspective, would be useful. Not urgent.

**Comment by AnthonyWharton** [comment]
Currently UH VPN does not offer multi factor authentication for connecting VPN clients.  However all VPN profiles are stored securely on the system once issued, and can be revoked remotely immediately from the web console.

- On Windows we use the [DPAPI](https://docs.microsoft.com/en-us/windows/win32/api/dpapi/nf-dpapi-cryptprotectdata) for per-user-per-machine encryption of profiles
- On Android we use the [androidx.security.crypto](https://developer.android.com/reference/androidx/security/crypto/package-summary) library which makes use of the [Android KeyStore](https://developer.android.com/training/articles/keystore).
- On iOS and macOS we use the local [Keychain](https://developer.apple.com/documentation/security/keychain_services).

We may look into MFA for VPN connections, but as of now this is not a priority and would require changing our infrastructure considerably.

**Comment by jwsi** [comment]
So from a cryptographic perspective all certificates issued for a server within a group are signed and generated by our root CA on the UH VPN API. For users that are unhappy with this process, the custom cryptography directive exists within the server configuration to allow people to roll their own crypto and use whatever certificates/keys they wish.

However, it must be said that for a given certificate type (e.g. RSA) and key size, there is no difference in security as to whether the certificate is self-signed or derived from a trusted source as long as the randomness source used in the generation process is of sufficient quality. If anything, a locally self-signed certificate generated by you has the ultimate level of trust because only you have seen the key. Both self-signed and trusted mechanisms undergo the same generation process, the only difference is that computers recognise certain certificates as trusted if their CA certificate is installed as a trusted root certificate within the operating system. This process is irrelevant to UH VPN as we distribute the CA certificate for a server to all devices with access to that server so that they can verify that the server certificate was signed by that CA. Therefore, the difference of self-signed and trusted certificates is irrelevant to UH VPN as separate verification checks take place instead of relying on the OS's trusted certificate store.

Authentication for connecting clients is handled via the exchange of a random 64 character hex password which is unique to each device created on UH VPN. During connection, this password is sent to the UH VPN API along with the device ID and person ID to ascertain whether to permit access to the group's network. This is more than sufficient from an entropy perspective and if a device were to be compromised, the revocation process for a device on UH VPN is far quicker and simpler to achieve for administrators than adding a certificate to a revocation list, then having to manually kick the user off the network.

Another point to add (that is often overlooked) is VPN profile distribution. Almost no articles online mention how many attacks on networks manifest themselves from adversaries gaining access to VPN profiles due to their distribution over insecure channels e.g. email. This is why UH VPN uses the unique one-time-code challenge system to distribute profiles to users over a HTTPS connection direct to the device. This removes any chance of side-channel attacks via profile distribution.

So to sum up, self-signed certificates are definitely not an issue here. As for MFA, this could be a useful feature, but raises additional questions such as "when should users be asked to re-authenticate?". Implementing MFA can actually come with additional headaches especially if users get tired of constantly entering MFA codes and eventually decide to not use the VPN and lose out on secure connectivity, so I'd argue that this feature is often a double edged sword. Moreover, UH VPN ensures that devices are re-authenticated every 30 minutes and during this process new symmetric keys are generated and exchanged for data channel encryption. This process queries the UH VPN API for an authentication challenge to ensure that the device is still permitted to connect. Therefore, if MFA was enabled, users would have to enter a code every 30 minutes to achieve the same level of forward secrecy!

James
