### ISSUE TITLE
BUG: Ubuntu 20.10 Groovy repository error

### ISSUE THREAD

**Issue by beatquantum** [ultrahorizon/UH-VPN-Docs#61]
**Describe the bug**
The Ubuntu installation step involves adding a repository, but it does not work on 20.10 Groovy

**To Reproduce**
1. Create a new Ubuntu 20.10 VPS.
2. Follow steps up to add repository 
3. apt update

**Expected behavior**
There needs to be a package for Groovy.

**Additional context**
A workaround was easy. I replaced Groovy with Focal in /etc/apt/ sources. Then ran apt update.

**Comment by jwsi** [comment]
Hey @beatquantum,

So UH VPN Server isn't officially available on Groovy as of yet. This is because there is no LTS release available for groovy at present and most people will be running bionic or focal.

However, adding support for groovy is in the pipeline and packages will be available on our beta PPA soon which will be merged into our stable branches in due course.

Although the altering of `/etc/apt/sources` may have worked in this case, I wouldn't recommend it again. There could be issues with the install process as there are specifics in place for different releases. E.g. common package dependencies will rely on what is available in the official groovy PPA and if these packages aren't compatible with UH VPN Server then it can cause issues.

I will reply here again when our groovy packages are released 👍 

James.
