### ISSUE TITLE
BUG: Probably a cipher mismatch problem.

### ISSUE THREAD

**Issue by beatquantum** [ultrahorizon/UH-VPN-Docs#62]
**Describe the bug**
I deleted the previous server and moved to a new server. Ubuntu 20.04. The logfile contents are attached showing many errors but the cipher mismatch could be the main reason.
[uh-logfile.txt](https://github.com/ultrahorizon/UH-VPN-Docs/files/5917490/uh-logfile.txt)
Relevant part of the openssl.cnf is also attached. 
[openssl.cnf.txt](https://github.com/ultrahorizon/UH-VPN-Docs/files/5917500/openssl.cnf.txt)

**To Reproduce**
1. Restrict openssl to these ciphers "TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305" - This can be easily done by adding the attached extract to the top of the openssl.cnf file as relevant to your OPENSSLDIR path.  (openssl version -a | grep DIR)
2. systemctl restart uh-vpn-server
3. See logfile

**Expected behavior**
The ciphers chosen according to our policy are strong and should work on security oriented architectures such as UH-VPN.

** Server
 - OS: [e.g. iOS] - Ubuntu 20.04.02 LTS
 - Version [e.g. 22] : uh-vpn-server 1.2.0

** Other info
Licence: Premium (Legacy)

**Comment by AnthonyWharton** [comment]
Hi @beatquantum,

Thanks, we'll take a look into this as soon as possible. However to take a quick punt for now, I imagine the issue is likely due to the fact that UH VPN uses AES-256-GCM with SHA256 hashing, along with a Curve-P 384 (secp384r1) for key negotiation.

Could you try allow AES-256-GCM with SHA256, as well as SHA384 as in your options to confirm this suspicion?

Thanks,
Anthony

**Comment by jwsi** [comment]
@beatquantum, @AnthonyWharton there isn't much to look at here, the cipher suite specified above is very strict and will probably cause issues with other software, not just UH VPN. E.g. TLS negotiations to webservers. What made you choose those ciphers specifically? A good place to start might be to look at Suite B accepted algorithms [here](https://en.wikipedia.org/wiki/NSA_Suite_B_Cryptography)

AES-256-GCM with ECDHE over curve P-384 is a well regarded cipher spec, I suggest you incorporate this into your selection to resolve the issue. **I will also update our server software to force this suite for users** because at the moment it can negotiate to "lesser" suites, but given that we are in control of both the client and server specifications via the UH VPN API, the risk of this is practically nil.

SHA-256 hashing is only used on the control channel as AES-256-GCM will do this automatically due to AEAD over the data channel.

James.

**Comment by beatquantum** [comment]
Even after adding 256, it did not work for me. The choice of ciphers was driven by another nginx server on the same vps. I am now moving to a standalone server that does not have cipher restriction.
