### ISSUE TITLE
BUG: Can not add profile by OTP

### ISSUE THREAD

**Issue by hybtoy** [ultrahorizon/UH-VPN-Docs#66]
Hello. Can't add profile with OTP. I get HTTP status 500. But management panel shows that OTP was used already. 
![Screenshot_20210401-222425_UH VPN](https://user-images.githubusercontent.com/12900872/113332010-14209d00-933a-11eb-8a20-125119c67efd.jpg)

**Comment by jwsi** [comment]
Hi @hybtoy,

Apologies for this. There was an update today within our JSON Web Token (JWT) creation logic for device profiles. It seems that a regression occured in the serialisation logic of these tokens and was causing this error.

This has since been fixed and should no longer occur. I do apologise if this has caused any issues. For any affected profiles, simply delete and re-create.

James.
