### ISSUE TITLE
Api key recieving problem

### ISSUE THREAD

**Issue by tkmw1985** [ultrahorizon/UH-VPN-Docs#76]
Hell dears !  

The problem is that clients cannot access the api keys!

I suppose that the program contacts your servers for api keys to get access? In my case, I think that access is blocked by the provider. If so, is there any way to solve this problem?

**Comment by AnthonyWharton** [comment]
Hi there, The app contacts the API for the following reasons:

 - In order to get a map of error codes to friendly error messages.
 - To sync new profiles
 - To update existing profiles

If you could please let us know where you saw an API error by providing slightly more information, that would be great.

If your communication to uh-vpn.com is blocked unfortunately there is not much you can do at this point, at this time clients need to be set up from a location that can access uh-vpn.com.
